// ================================================================
// Shared tooltip
// ================================================================
const tooltip = {
  el: null,
  init() { this.el = document.getElementById('chartTooltip'); },
  show(e, html) {
    if (!this.el) this.init();
    this.el.innerHTML = html;
    this.el.style.display = 'block';
    const r = this.el.getBoundingClientRect();
    let x = e.clientX + 12, y = e.clientY + 12;
    if (x + r.width > window.innerWidth - 8) x = e.clientX - r.width - 12;
    if (y + r.height > window.innerHeight - 8) y = e.clientY - r.height - 12;
    this.el.style.left = x + 'px';
    this.el.style.top = y + 'px';
  },
  hide() { if (this.el) this.el.style.display = 'none'; }
};

// Attach hover handlers to a canvas. hitTest(x, y) returns HTML string or null.
function addCanvasHover(canvasId, hitTest) {
  const canvas = document.getElementById(canvasId);
  canvas.addEventListener('mousemove', (e) => {
    const rect = canvas.getBoundingClientRect();
    const scaleX = canvas.width / (canvas.clientWidth || 1);
    const scaleY = canvas.height / (canvas.clientHeight || 1);
    const x = (e.clientX - rect.left) * scaleX / (window.devicePixelRatio || 1);
    const y = (e.clientY - rect.top) * scaleY / (window.devicePixelRatio || 1);
    const html = hitTest(x, y);
    if (html) tooltip.show(e, html);
    else tooltip.hide();
  });
  canvas.addEventListener('mouseleave', () => tooltip.hide());
}

// Hit zone storage for each chart (populated during render)
const hitZones = {};

// ================================================================
// NHTSA FARS National Data
// Sources: NHTSA FARS, FHWA VM-1, NHTSA Traffic Safety Facts
// ================================================================

const FARS_NATIONAL = [
  { year: 2014, fatalities: 32744, vmt: 3.03, rate: 1.08 },
  { year: 2015, fatalities: 35485, vmt: 3.10, rate: 1.15 },
  { year: 2016, fatalities: 37806, vmt: 3.17, rate: 1.19 },
  { year: 2017, fatalities: 37473, vmt: 3.21, rate: 1.17 },
  { year: 2018, fatalities: 36835, vmt: 3.24, rate: 1.14 },
  { year: 2019, fatalities: 36355, vmt: 3.26, rate: 1.11 },
  { year: 2020, fatalities: 39007, vmt: 2.83, rate: 1.34 },
  { year: 2021, fatalities: 42939, vmt: 3.13, rate: 1.37 },
  { year: 2022, fatalities: 42721, vmt: 3.19, rate: 1.34 },
  { year: 2023, fatalities: 40901, vmt: 3.25, rate: 1.26 },
  { year: 2024, fatalities: 39345, vmt: 3.28, rate: 1.20, estimate: true }
];

// Fatalities by road user type (FARS final counts)
const FARS_BY_TYPE = [
  { year: 2014, passengerCar: 12543, lightTruck: 8326, motorcycle: 4594, pedestrian: 4910, pedalcyclist: 723 },
  { year: 2015, passengerCar: 13320, lightTruck: 9067, motorcycle: 5026, pedestrian: 5495, pedalcyclist: 828 },
  { year: 2016, passengerCar: 14057, lightTruck: 9533, motorcycle: 5337, pedestrian: 6080, pedalcyclist: 848 },
  { year: 2017, passengerCar: 13902, lightTruck: 9620, motorcycle: 5229, pedestrian: 6075, pedalcyclist: 800 },
  { year: 2018, passengerCar: 13260, lightTruck: 9439, motorcycle: 5038, pedestrian: 6374, pedalcyclist: 868 },
  { year: 2019, passengerCar: 12535, lightTruck: 9649, motorcycle: 5044, pedestrian: 6272, pedalcyclist: 856 },
  { year: 2020, passengerCar: 10230, lightTruck: 11399, motorcycle: 5579, pedestrian: 6516, pedalcyclist: 938 },
  { year: 2021, passengerCar: 10897, lightTruck: 12818, motorcycle: 5932, pedestrian: 7485, pedalcyclist: 966 },
  { year: 2022, passengerCar: 10710, lightTruck: 12808, motorcycle: 6218, pedestrian: 7502, pedalcyclist: 1048 },
  { year: 2023, passengerCar: 10096, lightTruck: 12314, motorcycle: 6108, pedestrian: 7318, pedalcyclist: 1075 }
];

// Occupant fatality rates per 100M VMT by vehicle class
const FARS_CLASS_RATES = [
  { year: 2014, passengerCar: 0.86, lightTruck: 0.69, motorcycle: 23.00, overall: 1.08 },
  { year: 2015, passengerCar: 0.90, lightTruck: 0.73, motorcycle: 25.63, overall: 1.15 },
  { year: 2016, passengerCar: 0.94, lightTruck: 0.73, motorcycle: 26.10, overall: 1.19 },
  { year: 2017, passengerCar: 0.95, lightTruck: 0.70, motorcycle: 25.95, overall: 1.17 },
  { year: 2018, passengerCar: 0.92, lightTruck: 0.67, motorcycle: 25.09, overall: 1.14 },
  { year: 2019, passengerCar: 0.87, lightTruck: 0.63, motorcycle: 25.60, overall: 1.11 },
  { year: 2020, passengerCar: 1.20, lightTruck: 0.73, motorcycle: 30.05, overall: 1.34 },
  { year: 2021, passengerCar: 1.25, lightTruck: 0.79, motorcycle: 31.64, overall: 1.37 },
  { year: 2022, passengerCar: 1.19, lightTruck: 0.76, motorcycle: 32.47, overall: 1.34 },
  { year: 2023, passengerCar: 1.08, lightTruck: 0.65, motorcycle: 31.39, overall: 1.26 }
];

// FARS Per-Model, Toxicology, and Model Year data loaded from external file
// Generated by fars_process.py from NHTSA FARS bulk CSV downloads
</script>
<script src="fars_output.js"></script>
<script>


// ================================================================
// State
// ================================================================
let farsMetric = 'deaths'; // 'deaths' or 'rate'
let filteredFars = [];

// ================================================================
// NHTSA Chart A: National Fatality Trends (dual-axis bar+line)
// ================================================================
function renderNationalChart() {
  const canvas = document.getElementById('nationalChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;
  const isDark = document.documentElement.classList.contains('dark');
  const textColor = isDark ? '#e0e0e0' : '#1a1a1a';
  const mutedColor = isDark ? '#999' : '#666';
  const gridColor = isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)';
  const font = getComputedStyle(document.body).fontFamily;

  const wrap = canvas.parentElement;
  const W = wrap.clientWidth - 32;
  const H = Math.min(300, Math.max(220, W * 0.45));

  canvas.style.width = W + 'px';
  canvas.style.height = H + 'px';
  canvas.width = W * dpr;
  canvas.height = H * dpr;
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, W, H);

  const padL = 60, padR = 55, padT = 20, padB = 40;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;
  const n = FARS_NATIONAL.length;
  const barW = Math.min(50, plotW / n * 0.55);
  const gap = plotW / n;

  // Scales
  const maxFat = Math.max(...FARS_NATIONAL.map(d => d.fatalities)) * 1.12;
  const minRate = Math.min(...FARS_NATIONAL.map(d => d.rate)) - 0.05;
  const maxRate = Math.max(...FARS_NATIONAL.map(d => d.rate)) + 0.05;

  function yFat(v) { return padT + plotH - (v / maxFat) * plotH; }
  function yRate(v) { return padT + plotH - ((v - minRate) / (maxRate - minRate)) * plotH; }
  function xCenter(i) { return padL + gap * i + gap / 2; }

  // Grid lines (fatalities axis)
  ctx.strokeStyle = gridColor;
  ctx.lineWidth = 1;
  for (let i = 0; i <= 4; i++) {
    const v = (maxFat / 4) * i;
    const y = yFat(v);
    ctx.beginPath();
    ctx.moveTo(padL, y);
    ctx.lineTo(W - padR, y);
    ctx.stroke();
  }

  // Bars
  FARS_NATIONAL.forEach((d, i) => {
    const x = xCenter(i) - barW / 2;
    const y = yFat(d.fatalities);
    const h = yFat(0) - y;
    ctx.fillStyle = d.estimate
      ? getComputedStyle(document.documentElement).getPropertyValue('--fars-estimate').trim()
      : getComputedStyle(document.documentElement).getPropertyValue('--fars-bar').trim();
    ctx.beginPath();
    ctx.roundRect(x, y, barW, h, [3, 3, 0, 0]);
    ctx.fill();

    // Year label
    ctx.fillStyle = mutedColor;
    ctx.font = '10px ' + font;
    ctx.textAlign = 'center';
    ctx.fillText(d.year + (d.estimate ? '*' : ''), xCenter(i), H - padB + 16);

    // Fatality count on bar
    ctx.fillStyle = textColor;
    ctx.font = '10px ' + font;
    ctx.fillText((d.fatalities / 1000).toFixed(1) + 'k', xCenter(i), y - 6);
  });

  // Line (rate)
  const lineColor = getComputedStyle(document.documentElement).getPropertyValue('--fars-line').trim();
  ctx.strokeStyle = lineColor;
  ctx.lineWidth = 2.5;
  ctx.lineJoin = 'round';
  ctx.beginPath();
  FARS_NATIONAL.forEach((d, i) => {
    const x = xCenter(i);
    const y = yRate(d.rate);
    if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
  });
  ctx.stroke();

  // Dots + rate labels
  FARS_NATIONAL.forEach((d, i) => {
    const x = xCenter(i);
    const y = yRate(d.rate);
    ctx.fillStyle = lineColor;
    ctx.beginPath();
    ctx.arc(x, y, 4, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = isDark ? '#fff' : lineColor;
    ctx.beginPath();
    ctx.arc(x, y, 2, 0, Math.PI * 2);
    ctx.fill();

    ctx.fillStyle = lineColor;
    ctx.font = 'bold 10px ' + font;
    ctx.textAlign = 'center';
    ctx.fillText(d.rate.toFixed(2), x, y - 10);
  });

  // Left axis label
  ctx.save();
  ctx.fillStyle = mutedColor;
  ctx.font = '9px ' + font;
  ctx.translate(12, padT + plotH / 2);
  ctx.rotate(-Math.PI / 2);
  ctx.textAlign = 'center';
  ctx.fillText('Total Fatalities', 0, 0);
  ctx.restore();

  // Right axis label
  ctx.save();
  ctx.fillStyle = lineColor;
  ctx.font = '9px ' + font;
  ctx.translate(W - 8, padT + plotH / 2);
  ctx.rotate(Math.PI / 2);
  ctx.textAlign = 'center';
  ctx.fillText('Rate / 100M VMT', 0, 0);
  ctx.restore();

  // Left axis ticks
  ctx.fillStyle = mutedColor;
  ctx.font = '9px ' + font;
  ctx.textAlign = 'right';
  for (let i = 0; i <= 4; i++) {
    const v = (maxFat / 4) * i;
    ctx.fillText(Math.round(v / 1000) + 'k', padL - 6, yFat(v) + 3);
  }

  // Right axis ticks
  ctx.fillStyle = lineColor;
  ctx.textAlign = 'left';
  const rSteps = 4;
  for (let i = 0; i <= rSteps; i++) {
    const v = minRate + ((maxRate - minRate) / rSteps) * i;
    ctx.fillText(v.toFixed(2), W - padR + 6, yRate(v) + 3);
  }

  // Hit zones
  hitZones.national = FARS_NATIONAL.map((d, i) => ({
    x: xCenter(i) - gap/2, y: padT, w: gap, h: plotH,
    html: '<b>' + d.year + (d.estimate ? ' (est.)' : '') + '</b><br>' +
      'Fatalities: ' + d.fatalities.toLocaleString() + '<br>' +
      'VMT: ' + d.vmt.toFixed(2) + ' trillion<br>' +
      'Rate: ' + d.rate.toFixed(2) + ' per 100M VMT'
  }));
}

// ================================================================
// NHTSA Chart B: Fatalities by Road User Type (stacked bars)
// ================================================================
function renderUserTypeChart() {
  const canvas = document.getElementById('userTypeChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;
  const isDark = document.documentElement.classList.contains('dark');
  const textColor = isDark ? '#e0e0e0' : '#1a1a1a';
  const mutedColor = isDark ? '#999' : '#666';
  const font = getComputedStyle(document.body).fontFamily;
  const cs = getComputedStyle(document.documentElement);

  const categories = [
    { key: 'passengerCar', label: 'Passenger Car', color: cs.getPropertyValue('--fars-passenger').trim() },
    { key: 'lightTruck',   label: 'Light Truck',   color: cs.getPropertyValue('--fars-light-truck').trim() },
    { key: 'motorcycle',   label: 'Motorcycle',    color: cs.getPropertyValue('--fars-motorcycle').trim() },
    { key: 'pedestrian',   label: 'Pedestrian',    color: cs.getPropertyValue('--fars-pedestrian').trim() },
    { key: 'pedalcyclist', label: 'Pedalcyclist',   color: cs.getPropertyValue('--fars-pedalcyclist').trim() }
  ];

  // Populate legend
  const legendEl = document.getElementById('userTypeLegend');
  legendEl.innerHTML = categories.map(c =>
    `<div class="legend-item"><div class="legend-swatch" style="background:${c.color}"></div> ${c.label}</div>`
  ).join('');

  const wrap = canvas.parentElement;
  const W = wrap.clientWidth - 32;
  const H = Math.min(280, Math.max(200, W * 0.42));

  canvas.style.width = W + 'px';
  canvas.style.height = H + 'px';
  canvas.width = W * dpr;
  canvas.height = H * dpr;
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, W, H);

  const padL = 55, padR = 20, padT = 15, padB = 35;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;
  const n = FARS_BY_TYPE.length;
  const barW = Math.min(55, plotW / n * 0.55);
  const gap = plotW / n;

  const maxTotal = Math.max(...FARS_BY_TYPE.map(d =>
    categories.reduce((s, c) => s + d[c.key], 0)
  )) * 1.08;

  function yVal(v) { return padT + plotH - (v / maxTotal) * plotH; }
  function xCenter(i) { return padL + gap * i + gap / 2; }

  // Stacked bars
  FARS_BY_TYPE.forEach((d, i) => {
    let cumulative = 0;
    categories.forEach(cat => {
      const val = d[cat.key];
      const yTop = yVal(cumulative + val);
      const yBot = yVal(cumulative);
      ctx.fillStyle = cat.color;
      ctx.fillRect(xCenter(i) - barW / 2, yTop, barW, yBot - yTop);
      cumulative += val;
    });

    // Year label
    ctx.fillStyle = mutedColor;
    ctx.font = '10px ' + font;
    ctx.textAlign = 'center';
    ctx.fillText(d.year, xCenter(i), H - padB + 16);

    // Total label
    const total = categories.reduce((s, c) => s + d[c.key], 0);
    ctx.fillStyle = textColor;
    ctx.font = '10px ' + font;
    ctx.fillText((total / 1000).toFixed(1) + 'k', xCenter(i), yVal(total) - 6);
  });

  // Y axis ticks
  ctx.fillStyle = mutedColor;
  ctx.font = '9px ' + font;
  ctx.textAlign = 'right';
  for (let i = 0; i <= 4; i++) {
    const v = (maxTotal / 4) * i;
    ctx.fillText(Math.round(v / 1000) + 'k', padL - 6, yVal(v) + 3);
  }

  // Populate summary cards for 2023
  const latest = FARS_BY_TYPE[FARS_BY_TYPE.length - 1];
  const total2023 = categories.reduce((s, c) => s + latest[c.key], 0);
  document.getElementById('utPassengerPct').textContent = Math.round(latest.passengerCar / total2023 * 100) + '%';
  document.getElementById('utTruckPct').textContent = Math.round(latest.lightTruck / total2023 * 100) + '%';
  document.getElementById('utMotoPct').textContent = Math.round(latest.motorcycle / total2023 * 100) + '%';
  document.getElementById('utVulnerablePct').textContent = Math.round((latest.pedestrian + latest.pedalcyclist) / total2023 * 100) + '%';

  // Hit zones
  hitZones.userType = FARS_BY_TYPE.map((d, i) => {
    const total = categories.reduce((s, c) => s + d[c.key], 0);
    return {
      x: xCenter(i) - gap/2, y: padT, w: gap, h: plotH,
      html: '<b>' + d.year + '</b><br>' +
        categories.map(c => c.label + ': ' + d[c.key].toLocaleString()).join('<br>') +
        '<br><b>Total: ' + total.toLocaleString() + '</b>'
    };
  });
}

// ================================================================
// NHTSA Chart C: Fatality Rate by Vehicle Class (horizontal bars)
// ================================================================
let classRateYear = 2023;

function initClassRateToggle() {
  const toggle = document.getElementById('classRateYearToggle');
  FARS_CLASS_RATES.forEach(d => {
    const btn = document.createElement('button');
    btn.className = 'toggle-btn' + (d.year === classRateYear ? ' active' : '');
    btn.textContent = d.year;
    btn.addEventListener('click', () => {
      classRateYear = d.year;
      toggle.querySelectorAll('.toggle-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      renderClassRateChart(d.year);
    });
    toggle.appendChild(btn);
  });
}

function renderClassRateChart(year) {
  year = year || classRateYear;
  const data = FARS_CLASS_RATES.find(d => d.year === year);
  if (!data) return;

  const canvas = document.getElementById('classRateChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;
  const isDark = document.documentElement.classList.contains('dark');
  const textColor = isDark ? '#e0e0e0' : '#1a1a1a';
  const mutedColor = isDark ? '#999' : '#666';
  const font = getComputedStyle(document.body).fontFamily;
  const cs = getComputedStyle(document.documentElement);

  const bars = [
    { label: 'Passenger Car', value: data.passengerCar, color: cs.getPropertyValue('--fars-passenger').trim() },
    { label: 'Light Truck',   value: data.lightTruck,   color: cs.getPropertyValue('--fars-light-truck').trim() },
    { label: 'Overall',       value: data.overall,      color: cs.getPropertyValue('--fars-overall').trim() }
  ];

  const wrap = canvas.parentElement;
  const W = wrap.clientWidth - 32;
  const barH = 34;
  const barGap = 14;
  const H = 20 + bars.length * (barH + barGap) + 10;

  canvas.style.width = W + 'px';
  canvas.style.height = H + 'px';
  canvas.width = W * dpr;
  canvas.height = H * dpr;
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, W, H);

  const labelW = 110;
  const rateW = 50;
  const padR = 10;
  const barAreaW = W - labelW - rateW - padR;
  const maxVal = Math.max(...bars.map(b => b.value)) * 1.15;

  bars.forEach((b, i) => {
    const y = 20 + i * (barH + barGap);
    const bw = Math.max(2, (b.value / maxVal) * barAreaW);

    // Label
    ctx.fillStyle = textColor;
    ctx.font = '11px ' + font;
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    ctx.fillText(b.label, labelW - 8, y + barH / 2);

    // Bar
    ctx.fillStyle = b.color;
    ctx.beginPath();
    ctx.roundRect(labelW, y, bw, barH, 3);
    ctx.fill();

    // Value
    ctx.fillStyle = textColor;
    ctx.textAlign = 'left';
    ctx.font = 'bold 11px ' + font;
    ctx.fillText(b.value.toFixed(2), labelW + bw + 6, y + barH / 2);
  });

  // Update motorcycle callout
  document.getElementById('motoCalloutRate').textContent = data.motorcycle.toFixed(2);
  document.getElementById('motoCalloutDetail').textContent = 'per 100M VMT (' + year + ')';

  // Hit zones
  hitZones.classRate = bars.map((b, i) => {
    const y = 20 + i * (barH + barGap);
    return {
      x: labelW, y: y, w: barAreaW, h: barH,
      html: '<b>' + b.label + ' (' + year + ')</b><br>' +
        'Rate: ' + b.value.toFixed(2) + ' per 100M VMT' +
        (b.label === 'Overall' ? '<br>Motorcycle: ' + data.motorcycle.toFixed(2) : '')
    };
  });
}

// ================================================================
// FARS Per-Model: helpers
// ================================================================
function farsClsColor(cls) {
  const cs = getComputedStyle(document.documentElement);
  switch (cls) {
    case 'Sedan':      return cs.getPropertyValue('--cls-sedan').trim();
    case 'SUV':        return cs.getPropertyValue('--cls-suv').trim();
    case 'Pickup':     return cs.getPropertyValue('--cls-pickup').trim();
    case 'Van':        return cs.getPropertyValue('--cls-van').trim();
    case 'Sports Car': return cs.getPropertyValue('--cls-sports').trim();
    default:           return '#999';
  }
}

function farsVehicleName(d) { return d.make + ' ' + d.model; }

function getFarsValue(d) {
  if (farsMetric === 'rate') return d.rate;
  return d.deaths;
}

// ================================================================
// FARS Per-Model: metric toggle
// ================================================================
function setFarsMetric(m) {
  farsMetric = m;
  document.getElementById('fmBtnDeaths').classList.toggle('active', m === 'deaths');
  document.getElementById('fmBtnRate').classList.toggle('active', m === 'rate');
  applyFarsFilters();
}

// ================================================================
// FARS Per-Model: filters & sort
// ================================================================
function applyFarsFilters() {
  const search = document.getElementById('fmSearch').value.toLowerCase();
  const clsFilter = document.getElementById('fmClassFilter').value;
  const sortMode = document.getElementById('fmSort').value;

  filteredFars = FARS_BY_MODEL.filter(d => {
    if (farsMetric === 'rate' && (d.rate === null || d.rate === undefined)) return false;
    if (search && !farsVehicleName(d).toLowerCase().includes(search) && !d.cls.toLowerCase().includes(search)) return false;
    if (clsFilter && d.cls !== clsFilter) return false;
    return true;
  });

  switch (sortMode) {
    case 'deaths-desc':
      filteredFars.sort((a, b) => b.deaths - a.deaths);
      break;
    case 'rate-desc':
      filteredFars.sort((a, b) => (b.rate || 0) - (a.rate || 0));
      break;
    case 'rate-asc':
      filteredFars.sort((a, b) => (a.rate || 999) - (b.rate || 999));
      break;
    case 'make':
      filteredFars.sort((a, b) => farsVehicleName(a).localeCompare(farsVehicleName(b)));
      break;
  }

  renderFarsModelChart();
  renderFarsModelTable();
  updateFarsSummary();
}

// ================================================================
// FARS Per-Model: summary cards
// ================================================================
function updateFarsSummary() {
  const withRate = FARS_BY_MODEL.filter(d => d.rate !== null);
  document.getElementById('fmCount').textContent = FARS_BY_MODEL.length;

  const byDeaths = [...FARS_BY_MODEL].sort((a, b) => b.deaths - a.deaths);
  document.getElementById('fmHighCount').textContent = farsVehicleName(byDeaths[0]);
  document.getElementById('fmHighCountDetail').textContent = byDeaths[0].deaths.toLocaleString() + ' deaths over 5 yrs';

  if (withRate.length > 0) {
    const byRate = [...withRate].sort((a, b) => b.rate - a.rate);
    document.getElementById('fmHighRate').textContent = farsVehicleName(byRate[0]);
    document.getElementById('fmHighRateDetail').textContent = byRate[0].rate + ' per 100M est. VMT';
    document.getElementById('fmLowRate').textContent = farsVehicleName(byRate[byRate.length - 1]);
    document.getElementById('fmLowRateDetail').textContent = byRate[byRate.length - 1].rate + ' per 100M est. VMT';
  }
}

// ================================================================
// FARS Per-Model: horizontal bar chart
// ================================================================
function renderFarsModelChart() {
  const canvas = document.getElementById('farsModelChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;

  const barHeight = 24;
  const barGap = 3;
  const labelWidth = 200;
  const rateWidth = 60;
  const rightPad = 16;
  const topPad = 10;

  const isMobile = window.innerWidth < 600;
  const effectiveLabelWidth = isMobile ? 120 : labelWidth;

  const totalItems = filteredFars.length;
  const chartHeight = topPad + totalItems * (barHeight + barGap) + 20;
  const chartWidth = canvas.parentElement.clientWidth - 32;

  canvas.style.width = chartWidth + 'px';
  canvas.style.height = chartHeight + 'px';
  canvas.width = chartWidth * dpr;
  canvas.height = chartHeight * dpr;
  ctx.scale(dpr, dpr);

  ctx.clearRect(0, 0, chartWidth, chartHeight);
  const isDark = document.documentElement.classList.contains('dark');
  const textColor = isDark ? '#e0e0e0' : '#1a1a1a';
  const mutedColor = isDark ? '#999' : '#666';
  const font = getComputedStyle(document.body).fontFamily;

  if (totalItems === 0) {
    ctx.fillStyle = mutedColor;
    ctx.font = '13px ' + font;
    ctx.textAlign = 'center';
    ctx.fillText('No vehicles match current filters', chartWidth / 2, 60);
    document.getElementById('fmChartCount').textContent = '0 vehicles shown';
    return;
  }

  document.getElementById('fmChartCount').textContent = totalItems + ' vehicle' + (totalItems !== 1 ? 's' : '') + ' shown';

  const maxVal = Math.max(...filteredFars.map(d => getFarsValue(d) || 0), 1);
  const barAreaWidth = chartWidth - effectiveLabelWidth - rateWidth - rightPad;

  filteredFars.forEach((d, i) => {
    const y = topPad + i * (barHeight + barGap);
    const val = getFarsValue(d);
    if (val === null || val === undefined) return;
    const barW = Math.max(1, (val / maxVal) * barAreaWidth);

    // Label
    ctx.fillStyle = textColor;
    ctx.font = (isMobile ? '9' : '10') + 'px ' + font;
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    let label = farsVehicleName(d);
    if (isMobile && label.length > 18) label = label.substring(0, 17) + '\u2026';
    ctx.fillText(label, effectiveLabelWidth - 8, y + barHeight / 2);

    // Bar (colored by body class)
    ctx.fillStyle = farsClsColor(d.cls);
    ctx.beginPath();
    ctx.roundRect(effectiveLabelWidth, y, barW, barHeight, 3);
    ctx.fill();

    // Value
    ctx.fillStyle = textColor;
    ctx.textAlign = 'left';
    ctx.font = '10px ' + font;
    const displayVal = farsMetric === 'rate' ? val.toFixed(2) : val.toLocaleString();
    ctx.fillText(displayVal, effectiveLabelWidth + barW + 6, y + barHeight / 2);
  });

  // Hit zones
  hitZones.farsModel = filteredFars.map((d, i) => {
    const y = topPad + i * (barHeight + barGap);
    const fleetStr = d.fleet ? (d.fleet / 1e6).toFixed(1) + 'M' : 'N/A';
    const rateStr = d.rate !== null ? d.rate.toFixed(2) + ' per 100M VMT' : 'N/A';
    return {
      x: 0, y: y, w: chartWidth, h: barHeight,
      html: '<b>' + farsVehicleName(d) + '</b> (' + d.cls + ')<br>' +
        'Deaths: ' + d.deaths.toLocaleString() + '<br>' +
        'Est. rate: ' + rateStr + '<br>' +
        'Annual sales: ' + d.annual.toLocaleString() + '<br>' +
        'Est. fleet: ' + fleetStr
    };
  });
}

// ================================================================
// FARS Per-Model: data table
// ================================================================
function renderFarsModelTable() {
  const tbody = document.getElementById('fmTableBody');
  document.getElementById('fmTableCount').textContent = filteredFars.length + ' vehicle' + (filteredFars.length !== 1 ? 's' : '');

  if (filteredFars.length === 0) {
    tbody.innerHTML = '<tr class="no-results"><td colspan="7">No vehicles match current filters</td></tr>';
    return;
  }

  tbody.innerHTML = filteredFars.map((d, i) => {
    const fleetStr = d.fleet ? (d.fleet / 1000000).toFixed(1) + 'M' : '\u2014';
    const rateStr = d.rate !== null ? d.rate.toFixed(2) : '\u2014';
    return '<tr>' +
      '<td>' + (i + 1) + '</td>' +
      '<td>' + farsVehicleName(d) + '</td>' +
      '<td>' + d.cls + '</td>' +
      '<td><strong>' + d.deaths.toLocaleString() + '</strong></td>' +
      '<td>' + d.annual.toFixed(0) + '</td>' +
      '<td>' + fleetStr + '</td>' +
      '<td>' + rateStr + '</td>' +
    '</tr>';
  }).join('');
}

// Table column sorting
document.querySelectorAll('#fmTable th').forEach(th => {
  th.addEventListener('click', () => {
    const col = th.dataset.fmcol;
    const wasAsc = th.classList.contains('sorted-asc');
    document.querySelectorAll('#fmTable th').forEach(h => {
      h.classList.remove('sorted', 'sorted-asc', 'sorted-desc');
    });
    const asc = !wasAsc;
    th.classList.add('sorted', asc ? 'sorted-asc' : 'sorted-desc');
    th.querySelector('.sort-arrow').textContent = asc ? '\u25B2' : '\u25BC';

    switch (col) {
      case 'rank':
      case 'deaths':
        filteredFars.sort((a, b) => asc ? a.deaths - b.deaths : b.deaths - a.deaths);
        break;
      case 'vehicle':
        filteredFars.sort((a, b) => asc ? farsVehicleName(a).localeCompare(farsVehicleName(b)) : farsVehicleName(b).localeCompare(farsVehicleName(a)));
        break;
      case 'class':
        filteredFars.sort((a, b) => asc ? a.cls.localeCompare(b.cls) : b.cls.localeCompare(a.cls));
        break;
      case 'annual':
        filteredFars.sort((a, b) => asc ? a.annual - b.annual : b.annual - a.annual);
        break;
      case 'fleet':
        filteredFars.sort((a, b) => asc ? (a.fleet || 0) - (b.fleet || 0) : (b.fleet || 0) - (a.fleet || 0));
        break;
      case 'rate':
        filteredFars.sort((a, b) => asc ? (a.rate || 999) - (b.rate || 999) : (b.rate || 0) - (a.rate || 0));
        break;
    }

    renderFarsModelTable();
    renderFarsModelChart();
  });
});

// ================================================================
// Toxicology: State & Functions
// ================================================================
let filteredTox = [];


function applyToxFilters() {
  if (!FARS_TOXICOLOGY || FARS_TOXICOLOGY.length === 0) return;
  const search = document.getElementById('toxSearch').value.toLowerCase();
  const clsFilter = document.getElementById('toxClassFilter').value;
  const sortMode = document.getElementById('toxSort').value;

  filteredTox = FARS_TOXICOLOGY.filter(d => {
    if (search && !(d.make + ' ' + d.model).toLowerCase().includes(search) && !d.cls.toLowerCase().includes(search)) return false;
    if (clsFilter && d.cls !== clsFilter) return false;
    return true;
  });

  switch (sortMode) {
    case 'any-desc': filteredTox.sort((a, b) => b.anyPct - a.anyPct); break;
    case 'alc-desc': filteredTox.sort((a, b) => b.alcPct - a.alcPct); break;
    case 'drug-desc': filteredTox.sort((a, b) => b.drugPct - a.drugPct); break;
    case 'any-asc': filteredTox.sort((a, b) => a.anyPct - b.anyPct); break;
    case 'any-raw-desc': filteredTox.sort((a, b) => b.any - a.any); break;
    case 'alc-raw-desc': filteredTox.sort((a, b) => b.alc - a.alc); break;
    case 'drug-raw-desc': filteredTox.sort((a, b) => b.drug - a.drug); break;
    case 'drivers-desc': filteredTox.sort((a, b) => b.drivers - a.drivers); break;
    case 'make': filteredTox.sort((a, b) => (a.make + ' ' + a.model).localeCompare(b.make + ' ' + b.model)); break;
  }

  renderToxChart();
  renderToxTable();
  updateToxSummary();
}

function updateToxSummary() {
  if (!FARS_TOXICOLOGY || FARS_TOXICOLOGY.length === 0) return;
  const totalDrivers = FARS_TOXICOLOGY.reduce((s, d) => s + d.drivers, 0);
  const totalAny = FARS_TOXICOLOGY.reduce((s, d) => s + d.any, 0);
  document.getElementById('toxOverallRate').textContent = (totalAny / totalDrivers * 100).toFixed(1) + '%';

  const sorted = [...FARS_TOXICOLOGY].sort((a, b) => b.anyPct - a.anyPct);
  document.getElementById('toxHighest').textContent = sorted[0].make + ' ' + sorted[0].model;
  document.getElementById('toxHighestDetail').textContent = sorted[0].anyPct + '% any impairment';
  const last = sorted[sorted.length - 1];
  document.getElementById('toxLowest').textContent = last.make + ' ' + last.model;
  document.getElementById('toxLowestDetail').textContent = last.anyPct + '% any impairment';
}

function toxShowRaw() {
  const sortMode = document.getElementById('toxSort').value;
  return sortMode.includes('-raw-') || sortMode === 'drivers-desc';
}

function renderToxChart() {
  const canvas = document.getElementById('toxChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;

  const subBarHeight = 7;
  const groupGap = 5;
  const groupHeight = subBarHeight * 3 + 2 + groupGap; // 3 bars + 2px internal gap + gap
  const labelWidth = 200;
  const rightPad = 80;
  const topPad = 10;
  const isMobile = window.innerWidth < 600;
  const effectiveLabelWidth = isMobile ? 120 : labelWidth;
  const showRaw = toxShowRaw();

  const totalItems = filteredTox.length;
  const chartHeight = topPad + totalItems * groupHeight + 20;
  const chartWidth = canvas.parentElement.clientWidth - 32;

  canvas.style.width = chartWidth + 'px';
  canvas.style.height = chartHeight + 'px';
  canvas.width = chartWidth * dpr;
  canvas.height = chartHeight * dpr;
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, chartWidth, chartHeight);

  const isDark = document.documentElement.classList.contains('dark');
  const textColor = isDark ? '#e0e0e0' : '#1a1a1a';
  const mutedColor = isDark ? '#999' : '#666';
  const font = getComputedStyle(document.body).fontFamily;
  const cs = getComputedStyle(document.documentElement);
  const colors = {
    any: cs.getPropertyValue('--tox-any').trim(),
    alc: cs.getPropertyValue('--tox-alcohol').trim(),
    drug: cs.getPropertyValue('--tox-drug').trim()
  };

  if (totalItems === 0) {
    ctx.fillStyle = mutedColor;
    ctx.font = '13px ' + font;
    ctx.textAlign = 'center';
    ctx.fillText('No vehicles match current filters', chartWidth / 2, 60);
    document.getElementById('toxChartCount').textContent = '0 vehicles shown';
    return;
  }

  document.getElementById('toxChartCount').textContent = totalItems + ' vehicle' + (totalItems !== 1 ? 's' : '') + ' shown';

  const barAreaWidth = chartWidth - effectiveLabelWidth - rightPad;
  const maxVal = showRaw
    ? Math.max(...filteredTox.map(d => d.any), 1)
    : Math.max(...filteredTox.map(d => d.anyPct), 1);

  const metrics = [
    { key: 'any', pctKey: 'anyPct', color: colors.any },
    { key: 'alc', pctKey: 'alcPct', color: colors.alc },
    { key: 'drug', pctKey: 'drugPct', color: colors.drug }
  ];

  filteredTox.forEach((d, i) => {
    const groupY = topPad + i * groupHeight;
    const labelY = groupY + (subBarHeight * 3 + 2) / 2;

    // Vehicle label
    ctx.fillStyle = textColor;
    ctx.font = (isMobile ? '9' : '10') + 'px ' + font;
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    let label = d.make + ' ' + d.model;
    if (isMobile && label.length > 18) label = label.substring(0, 17) + '\u2026';
    ctx.fillText(label, effectiveLabelWidth - 8, labelY);

    // 3 bars
    metrics.forEach((m, mi) => {
      const y = groupY + mi * (subBarHeight + 1);
      const val = showRaw ? d[m.key] : d[m.pctKey];
      const barW = Math.max(1, (val / maxVal) * barAreaWidth);

      ctx.fillStyle = m.color;
      ctx.beginPath();
      ctx.roundRect(effectiveLabelWidth, y, barW, subBarHeight, 2);
      ctx.fill();
    });

    // Value label (show the primary metric's value)
    const primaryVal = showRaw ? d.any : d.anyPct;
    const anyBarW = Math.max(1, (primaryVal / maxVal) * barAreaWidth);
    ctx.fillStyle = mutedColor;
    ctx.textAlign = 'left';
    ctx.font = '9px ' + font;
    const valText = showRaw
      ? d.any.toLocaleString() + ' / ' + d.alc.toLocaleString() + ' / ' + d.drug.toLocaleString()
      : d.anyPct + '% / ' + d.alcPct + '% / ' + d.drugPct + '%';
    ctx.fillText(valText, effectiveLabelWidth + Math.max(anyBarW, (showRaw ? d[metrics[0].key] : d[metrics[0].pctKey]) / maxVal * barAreaWidth) + 6, labelY);
  });

  // Hit zones
  hitZones.tox = filteredTox.map((d, i) => {
    const groupY = topPad + i * groupHeight;
    return {
      x: 0, y: groupY, w: chartWidth, h: groupHeight - groupGap,
      html: '<b>' + d.make + ' ' + d.model + '</b> (' + d.cls + ')<br>' +
        'Drivers in fatal crashes: ' + d.drivers.toLocaleString() + '<br>' +
        'Any impairment: ' + d.any.toLocaleString() + ' (' + d.anyPct + '%)<br>' +
        'Alcohol: ' + d.alc.toLocaleString() + ' (' + d.alcPct + '%)<br>' +
        'Drugs: ' + d.drug.toLocaleString() + ' (' + d.drugPct + '%)'
    };
  });
}

function renderToxTable() {
  const tbody = document.getElementById('toxTableBody');
  document.getElementById('toxTableCount').textContent = filteredTox.length + ' vehicle' + (filteredTox.length !== 1 ? 's' : '');

  if (filteredTox.length === 0) {
    tbody.innerHTML = '<tr class="no-results"><td colspan="10">No vehicles match current filters</td></tr>';
    return;
  }

  tbody.innerHTML = filteredTox.map((d, i) =>
    '<tr>' +
    '<td>' + (i + 1) + '</td>' +
    '<td>' + d.make + ' ' + d.model + '</td>' +
    '<td>' + d.cls + '</td>' +
    '<td>' + d.drivers.toLocaleString() + '</td>' +
    '<td><strong>' + d.anyPct + '%</strong></td>' +
    '<td>' + d.any.toLocaleString() + '</td>' +
    '<td>' + d.alcPct + '%</td>' +
    '<td>' + d.alc.toLocaleString() + '</td>' +
    '<td>' + d.drugPct + '%</td>' +
    '<td>' + d.drug.toLocaleString() + '</td>' +
    '</tr>'
  ).join('');
}

// Toxicology table column sorting
document.querySelectorAll('#toxTable th').forEach(th => {
  th.addEventListener('click', () => {
    const col = th.dataset.toxcol;
    const wasAsc = th.classList.contains('sorted-asc');
    document.querySelectorAll('#toxTable th').forEach(h => {
      h.classList.remove('sorted', 'sorted-asc', 'sorted-desc');
    });
    const asc = !wasAsc;
    th.classList.add('sorted', asc ? 'sorted-asc' : 'sorted-desc');
    th.querySelector('.sort-arrow').textContent = asc ? '\u25B2' : '\u25BC';

    switch (col) {
      case 'rank': case 'any':
        filteredTox.sort((a, b) => asc ? a.anyPct - b.anyPct : b.anyPct - a.anyPct); break;
      case 'any-raw':
        filteredTox.sort((a, b) => asc ? a.any - b.any : b.any - a.any); break;
      case 'vehicle':
        filteredTox.sort((a, b) => asc ? (a.make + a.model).localeCompare(b.make + b.model) : (b.make + b.model).localeCompare(a.make + a.model)); break;
      case 'class':
        filteredTox.sort((a, b) => asc ? a.cls.localeCompare(b.cls) : b.cls.localeCompare(a.cls)); break;
      case 'drivers':
        filteredTox.sort((a, b) => asc ? a.drivers - b.drivers : b.drivers - a.drivers); break;
      case 'alc':
        filteredTox.sort((a, b) => asc ? a.alcPct - b.alcPct : b.alcPct - a.alcPct); break;
      case 'alc-raw':
        filteredTox.sort((a, b) => asc ? a.alc - b.alc : b.alc - a.alc); break;
      case 'drug':
        filteredTox.sort((a, b) => asc ? a.drugPct - b.drugPct : b.drugPct - a.drugPct); break;
      case 'drug-raw':
        filteredTox.sort((a, b) => asc ? a.drug - b.drug : b.drug - a.drug); break;
    }
    renderToxTable();
    renderToxChart();
  });
});

// ================================================================
// Model Year: State & Functions
// ================================================================
let myearSelected = []; // array of {make, model, cls} objects, max 5
const MYEAR_COLORS = ['--myear-1', '--myear-2', '--myear-3', '--myear-4', '--myear-5'];

function applyMyearSearch() {
  const input = document.getElementById('myearSearch');
  const val = input.value.trim();
  const datalist = document.getElementById('myearDatalist');

  // Populate datalist with matching models
  if (val.length >= 2 && FARS_MODEL_YEAR && FARS_MODEL_YEAR.length > 0) {
    const lower = val.toLowerCase();
    const matches = FARS_MODEL_YEAR.filter(d =>
      (d.make + ' ' + d.model).toLowerCase().includes(lower)
    ).slice(0, 10);
    datalist.innerHTML = matches.map(d =>
      '<option value="' + d.make + ' ' + d.model + '">'
    ).join('');
  }

  // Check for exact match selection
  if (FARS_MODEL_YEAR) {
    const match = FARS_MODEL_YEAR.find(d =>
      (d.make + ' ' + d.model).toLowerCase() === val.toLowerCase()
    );
    if (match && myearSelected.length < 5 &&
        !myearSelected.some(s => s.make === match.make && s.model === match.model)) {
      myearSelected.push({ make: match.make, model: match.model, cls: match.cls });
      input.value = '';
      datalist.innerHTML = '';
      renderMyearChips();
      renderMyearChart();
    }
  }
}

function removeMyearSelection(idx) {
  myearSelected.splice(idx, 1);
  renderMyearChips();
  renderMyearChart();
}

function renderMyearChips() {
  const container = document.getElementById('myearChips');
  const cs = getComputedStyle(document.documentElement);
  container.innerHTML = myearSelected.map((s, i) => {
    const color = cs.getPropertyValue(MYEAR_COLORS[i]).trim();
    return '<span class="chip" onclick="removeMyearSelection(' + i + ')" style="border-color:' + color + '">' +
      '<span style="color:' + color + '">\u25CF</span> ' +
      s.make + ' ' + s.model +
      ' <span class="chip-x">\u2715</span></span>';
  }).join('');
}

function renderMyearChart() {
  const canvas = document.getElementById('myearChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;
  const isDark = document.documentElement.classList.contains('dark');
  const textColor = isDark ? '#e0e0e0' : '#1a1a1a';
  const mutedColor = isDark ? '#999' : '#666';
  const gridColor = isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)';
  const font = getComputedStyle(document.body).fontFamily;
  const cs = getComputedStyle(document.documentElement);

  const wrap = canvas.parentElement;
  const W = wrap.clientWidth - 32;
  const H = Math.min(350, Math.max(250, W * 0.45));

  canvas.style.width = W + 'px';
  canvas.style.height = H + 'px';
  canvas.width = W * dpr;
  canvas.height = H * dpr;
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, W, H);

  if (myearSelected.length === 0 || !FARS_MODEL_YEAR || FARS_MODEL_YEAR.length === 0) {
    ctx.fillStyle = mutedColor;
    ctx.font = '13px ' + font;
    ctx.textAlign = 'center';
    ctx.fillText('Search and select vehicles above to compare model years', W / 2, H / 2);
    return;
  }

  // Gather data series
  const series = myearSelected.map((sel, i) => {
    const entry = FARS_MODEL_YEAR.find(d => d.make === sel.make && d.model === sel.model);
    return {
      label: sel.make + ' ' + sel.model,
      color: cs.getPropertyValue(MYEAR_COLORS[i]).trim(),
      years: entry ? entry.years : {},
    };
  });

  // Find year range and max value
  let allYears = new Set();
  let maxVal = 0;
  series.forEach(s => {
    Object.entries(s.years).forEach(([y, d]) => {
      allYears.add(parseInt(y));
      if (d > maxVal) maxVal = d;
    });
  });
  const years = [...allYears].sort((a, b) => a - b);
  if (years.length === 0) return;
  maxVal *= 1.1;

  const padL = 55, padR = 20, padT = 20, padB = 40;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;

  function xPos(yr) { return padL + ((yr - years[0]) / (years[years.length - 1] - years[0] || 1)) * plotW; }
  function yPos(v) { return padT + plotH - (v / maxVal) * plotH; }

  // Grid
  ctx.strokeStyle = gridColor;
  ctx.lineWidth = 1;
  for (let i = 0; i <= 4; i++) {
    const v = (maxVal / 4) * i;
    const y = yPos(v);
    ctx.beginPath();
    ctx.moveTo(padL, y);
    ctx.lineTo(W - padR, y);
    ctx.stroke();
  }

  // Y axis ticks
  ctx.fillStyle = mutedColor;
  ctx.font = '9px ' + font;
  ctx.textAlign = 'right';
  for (let i = 0; i <= 4; i++) {
    const v = (maxVal / 4) * i;
    ctx.fillText(Math.round(v), padL - 6, yPos(v) + 3);
  }

  // X axis labels
  ctx.textAlign = 'center';
  const yearStep = Math.max(1, Math.floor(years.length / 10));
  years.forEach((yr, i) => {
    if (i % yearStep === 0 || yr === years[years.length - 1]) {
      ctx.fillText(yr, xPos(yr), H - padB + 16);
    }
  });

  // Draw lines
  series.forEach(s => {
    const pts = years.filter(y => s.years[y] !== undefined).map(y => ({ x: xPos(y), y: yPos(s.years[y]) }));
    if (pts.length < 2) return;

    ctx.strokeStyle = s.color;
    ctx.lineWidth = 2.5;
    ctx.lineJoin = 'round';
    ctx.beginPath();
    pts.forEach((p, i) => { if (i === 0) ctx.moveTo(p.x, p.y); else ctx.lineTo(p.x, p.y); });
    ctx.stroke();

    // Dots
    pts.forEach(p => {
      ctx.fillStyle = s.color;
      ctx.beginPath();
      ctx.arc(p.x, p.y, 3, 0, Math.PI * 2);
      ctx.fill();
    });
  });

  // Y axis label
  ctx.save();
  ctx.fillStyle = mutedColor;
  ctx.font = '9px ' + font;
  ctx.translate(12, padT + plotH / 2);
  ctx.rotate(-Math.PI / 2);
  ctx.textAlign = 'center';
  ctx.fillText('Deaths', 0, 0);
  ctx.restore();

  // Hit zones — one per data point
  hitZones.myear = [];
  series.forEach(s => {
    years.forEach(yr => {
      if (s.years[yr] === undefined) return;
      const deaths = s.years[yr];
      hitZones.myear.push({
        x: xPos(yr) - 8, y: yPos(deaths) - 8, w: 16, h: 16,
        html: '<b>' + s.label + '</b><br>' +
          'Model year: ' + yr + '<br>' +
          'Deaths: ' + deaths.toLocaleString()
      });
    });
  });
}

function updateMyearSummary() {
  if (!FARS_MODEL_YEAR || FARS_MODEL_YEAR.length === 0) return;
  let minYear = 9999, maxYear = 0;
  const yearTotals = {};
  FARS_MODEL_YEAR.forEach(d => {
    Object.entries(d.years).forEach(([y, deaths]) => {
      const yr = parseInt(y);
      if (yr < minYear) minYear = yr;
      if (yr > maxYear) maxYear = yr;
      yearTotals[yr] = (yearTotals[yr] || 0) + deaths;
    });
  });
  document.getElementById('myearRange').textContent = minYear + '\u2013' + maxYear;
  const peakEntry = Object.entries(yearTotals).sort((a, b) => b[1] - a[1])[0];
  if (peakEntry) {
    document.getElementById('myearPeak').textContent = peakEntry[0];
    document.getElementById('myearPeakDetail').textContent = peakEntry[1].toLocaleString() + ' deaths across all models';
  }
}

// ================================================================
// Tab navigation
// ================================================================
const TAB_CHARTS = {
  model: () => renderFarsModelChart(),
  tox: () => { if (typeof renderToxChart === 'function') renderToxChart(); },
  myear: () => { if (typeof renderMyearChart === 'function') renderMyearChart(); },
  national: () => { renderNationalChart(); renderUserTypeChart(); renderClassRateChart(); },
  method: () => {}
};

function switchTab(id) {
  document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  const pane = document.getElementById('tab-' + id);
  if (pane) pane.classList.add('active');
  const btns = document.querySelectorAll('.tab-btn');
  const names = ['model','tox','myear','national','method'];
  const idx = names.indexOf(id);
  if (idx >= 0 && btns[idx]) btns[idx].classList.add('active');
  history.replaceState(null, '', '#' + id);
  // Re-render charts in newly visible pane (they need non-zero width)
  requestAnimationFrame(() => { if (TAB_CHARTS[id]) TAB_CHARTS[id](); });
}

// ================================================================
// Resize handler
// ================================================================
let resizeTimer;
window.addEventListener('resize', () => {
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(() => {
    // Only re-render charts in the active tab
    const active = document.querySelector('.tab-pane.active');
    if (active) {
      const id = active.id.replace('tab-', '');
      if (TAB_CHARTS[id]) TAB_CHARTS[id]();
    }
  }, 150);
});

// ================================================================
// Initialize
// ================================================================
initClassRateToggle();
applyFarsFilters();
applyToxFilters();
updateMyearSummary();
// Pre-select top 5 most dangerous models by estimated rate for model year chart
if (FARS_BY_MODEL && FARS_MODEL_YEAR && FARS_BY_MODEL.length > 0) {
  const myearSet = new Set(FARS_MODEL_YEAR.map(d => d.make + '|' + d.model));
  const top5 = FARS_BY_MODEL
    .filter(d => d.rate !== null && myearSet.has(d.make + '|' + d.model))
    .sort((a, b) => b.rate - a.rate)
    .slice(0, 5);
  top5.forEach(d => myearSelected.push({ make: d.make, model: d.model, cls: d.cls }));
  renderMyearChips();
}
// Activate tab from hash or default to 'model'
const initTab = location.hash.replace('#', '') || 'model';
switchTab(['model','tox','myear','national','method'].includes(initTab) ? initTab : 'model');

// Hover tooltips for all charts
addCanvasHover('nationalChart', (x, y) => {
  const z = (hitZones.national || []).find(h => x >= h.x && x <= h.x + h.w && y >= h.y && y <= h.y + h.h);
  return z ? z.html : null;
});
addCanvasHover('userTypeChart', (x, y) => {
  const z = (hitZones.userType || []).find(h => x >= h.x && x <= h.x + h.w && y >= h.y && y <= h.y + h.h);
  return z ? z.html : null;
});
addCanvasHover('classRateChart', (x, y) => {
  const z = (hitZones.classRate || []).find(h => x >= h.x && x <= h.x + h.w && y >= h.y && y <= h.y + h.h);
  return z ? z.html : null;
});
addCanvasHover('farsModelChart', (x, y) => {
  const z = (hitZones.farsModel || []).find(h => x >= h.x && x <= h.x + h.w && y >= h.y && y <= h.y + h.h);
  return z ? z.html : null;
});
addCanvasHover('toxChart', (x, y) => {
  const z = (hitZones.tox || []).find(h => x >= h.x && x <= h.x + h.w && y >= h.y && y <= h.y + h.h);
  return z ? z.html : null;
});
addCanvasHover('myearChart', (x, y) => {
  const z = (hitZones.myear || []).find(h => x >= h.x && x <= h.x + h.w && y >= h.y && y <= h.y + h.h);
  return z ? z.html : null;
});

// Theme toggle
(function() {
  var btn = document.createElement('button');
  btn.className = 'theme-toggle';
  function label() {
    var t = localStorage.getItem('theme');
    btn.textContent = t === 'dark' ? 'dark' : t === 'light' ? 'light' : 'auto';
  }
  btn.addEventListener('click', function() {
    var t = localStorage.getItem('theme');
    var next = !t ? 'dark' : t === 'dark' ? 'light' : null;
    if (next) localStorage.setItem('theme', next); else localStorage.removeItem('theme');
    var isDark = next === 'dark' || (!next && window.matchMedia('(prefers-color-scheme: dark)').matches);
    document.documentElement.classList.toggle('dark', isDark);
    label();
    // Re-render charts in active tab with updated theme colors
    var active = document.querySelector('.tab-pane.active');
    if (active && TAB_CHARTS) {
      var tid = active.id.replace('tab-', '');
      if (TAB_CHARTS[tid]) TAB_CHARTS[tid]();
    }
  });
  label();
  document.body.appendChild(btn);
})();
